### ISSUE TITLE
Prompt Syntax Highlighting hides text enabling is wrapped wrong

### ISSUE THREAD

**Issue by picobyte** [canisminor1990/sd-webui-lobe-theme#332]
Effectively rendering the interface unusable. Only the positive prompt is invisible. If I inspect element I see to the right:
```css
element.style {
    overflow-y: scroll;
    height: 84px;
    color: transparent;
    caret-color: rgb(196, 240, 66);
}
```
If I uncheck the `color: transparent` with the Prompt Syntax Highlighting  enabled, that problem goes away.
The word wrapping issue is mentioned in #265 The hidden text I also mentioned [here](https://github.com/lobehub/lobe-ui/issues/36)
